# Generated by Django 3.2 on 2022-08-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
