# Generated by Django 3.2 on 2022-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20220816_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
