# Generated by Django 3.2 on 2022-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=models.CharField(default='UK', max_length=40),
            preserve_default=False,
        ),
    ]
