# Generated by Django 3.2 on 2022-08-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
