# Generated by Django 3.2 on 2022-08-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscription_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='full_name',
        ),
    ]
