# Generated by Django 3.2 on 2022-08-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_rename_name_subscription_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionlineitem',
            old_name='order',
            new_name='subscription',
        ),
    ]
