# Generated by Django 3.2 on 2022-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_rename_order_subscriptionlineitem_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
