# Generated by Django 3.2 on 2022-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20220818_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
