# Generated by Django 3.2 on 2022-09-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_alter_subscription_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_number',
            new_name='order_number',
        ),
    ]
