# Generated by Django 3.2 on 2022-07-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220728_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
