# Generated by Django 3.2 on 2022-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220728_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default='14.99', max_digits=5),
        ),
    ]
