# Generated by Django 3.2 on 2022-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220728_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='14.99', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('1', '1 kg'), ('2', '2 kg'), ('3', '3 kg'), ('4', '4 kg'), ('5', '5 kg')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
