# Generated by Django 3.2 on 2022-08-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220812_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_one', models.CharField(default='You need an ingredient', max_length=35)),
                ('ingredient_two', models.CharField(blank=True, max_length=35)),
                ('ingredient_three', models.CharField(blank=True, max_length=35)),
                ('ingredient_four', models.CharField(blank=True, max_length=35)),
                ('ingredient_five', models.CharField(blank=True, max_length=35)),
                ('ingredient_six', models.CharField(blank=True, max_length=35)),
                ('ingredient_seven', models.CharField(blank=True, max_length=35)),
                ('ingredient_eight', models.CharField(blank=True, max_length=35)),
                ('ingredient_nine', models.CharField(blank=True, max_length=35)),
                ('ingredient_ten', models.CharField(blank=True, max_length=35)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='products.product')),
            ],
        ),
    ]
