# Generated by Django 3.2 on 2022-08-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220816_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={'verbose_name_plural': 'Nutrition'},
        ),
    ]
