# Generated by Django 3.2 on 2022-08-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_one',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_eight',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_five',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_four',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_nine',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_seven',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_six',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_ten',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_three',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_two',
        ),
    ]
